#!/usr/bin/env bash
# Propagate the single-source-of-truth version from ./VERSION into:
#   - frontend/package.json
#   - backend/package.json
#   - frontend/src/version.ts (APP_VERSION)
#
# Usage:
#   ./scripts/sync-version.sh           # sync to value already in VERSION
#   ./scripts/sync-version.sh 2.3.0     # write new version to VERSION and sync
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VERSION_FILE="$ROOT/VERSION"

if [[ $# -ge 1 ]]; then
  echo "$1" > "$VERSION_FILE"
fi

if [[ ! -f "$VERSION_FILE" ]]; then
  echo "ERROR: $VERSION_FILE is missing." >&2
  exit 1
fi

VERSION="$(tr -d ' \t\r\n' < "$VERSION_FILE")"
if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+([.-][0-9A-Za-z.-]+)?$ ]]; then
  echo "ERROR: version '$VERSION' is not semver-like." >&2
  exit 1
fi

# Surgically replace the top-level "version" field in package.json files so
# the rest of the file (formatting, comments, ordering) is preserved.
node - "$VERSION" "$ROOT/frontend/package.json" "$ROOT/backend/package.json" <<'NODE'
const fs = require('fs');
const [version, ...paths] = process.argv.slice(2);
for (const p of paths) {
  const src = fs.readFileSync(p, 'utf8');
  const next = src.replace(
    /("version"\s*:\s*")[^"]+(")/,
    (_m, a, b) => `${a}${version}${b}`,
  );
  if (next === src) {
    console.warn(`no "version" field found in ${p}; skipping`);
    continue;
  }
  fs.writeFileSync(p, next);
  console.log(`updated ${p} -> ${version}`);
}
NODE

cat > "$ROOT/frontend/src/version.ts" <<EOF
// Generated by scripts/sync-version.sh from /VERSION — do not edit by hand.
export const APP_VERSION = '$VERSION';
EOF
echo "updated $ROOT/frontend/src/version.ts -> $VERSION"

echo "Done. VERSION=$VERSION"
